---
name: Release

on:  # yamllint disable rule:truthy
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Test
        run: bazel test //...
        working-directory: tests/bcr

  test-mac:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Test
        run: bazel test //...
        working-directory: tests/bcr


  pkg:
    runs-on: ubuntu-latest
    needs:
      - build
      - test-mac
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create release archive and notes
        run: |
          scripts/package_distro.sh

      - name: Archive release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: |
            bazel-bin/distro/*.tar.gz
            bazel-bin/distro/relnotes.md
          retention-days: 5

  release:
    if: ${{ github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    needs: pkg
    permissions:
      contents: write
    steps:
      - name: Download release artifacts
        uses: actions/download-artifact@v4
        with:
          name: release

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: relnotes.md
          fail_on_unmatched_files: true
          files: rules_tf-*.tar.gz
