---
name: CI

on:  # yamllint disable rule:truthy
  push:
    branches:
      - main
    tags:
      - "*.*.*"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Test
        run: bazel test //...
        working-directory: tests/bcr

  test-mac:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Test
        run: bazel test //...
        working-directory: tests/bcr


  pkg:
    runs-on: ubuntu-latest
    needs:
      - build
      - test-mac
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create release archive and notes
        run: |
          bazel build //distro

      - name: Archive release artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: bazel-bin/distro/*.tar.gz,bazel-bin/distro/*.txt,
          retention-days: 5

  release:
    if: ${{ github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    needs: pkg
    steps:
      - name: Download release artifacts
        uses: actions/download-artifact@v3
        with:
          name: release

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: relnotes.txt
          fail_on_unmatched_files: true
          files: rules_tf-*.tar.gz
